###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: gallery-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=galllery
        - MYSQL_USER=galllery
        - MYSQL_PASSWORD=galllery
      ports:
        - "9052:3306"

    webserver:
      image: nginx:alpine
      container_name: gallery-webserver
      working_dir: /application
      depends_on:
        - php-fpm
      links:
        - php-fpm
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "9050:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: gallery-php-fpm
      working_dir: /application
      restart: always
      links:
        - mysql
      depends_on:
        - mysql
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

#
#    node:
#      build:
#        context: .
#        dockerfile: phpdocker/node/Dockerfile
#      working_dir: /application
#      restart: always
#      depends_on:
#        - php-fpm
#      volumes:
#        - .:/application
